version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - redis
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    image: votingbuck-backend_server
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/.env
      # - ./:/app
      # - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - redis
  redis:
    image: redislabs/redisearch
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - /local-data/:/data
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
